version: '3'
services:
  db:
    build:
      context: ./database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres-data:
