# Use the official PostgreSQL image as base
FROM postgres:12

# Set environment variables for PostgreSQL
ENV POSTGRES_DB myapp_production
ENV POSTGRES_USER myapp_user
ENV POSTGRES_PASSWORD pavan1234

# Expose the PostgreSQL port
EXPOSE 5432
